### ISSUE TITLE
Need to expose additional functionality from the jquery tooltipster plugin

### ISSUE THREAD

**Issue by karanjthakkar** [altrim/ember-cli-tooltipster#10]
Additional properties `onlyOne` and `autoClose` need to be exposed. If not this, then provide support to expose these properties from a custom component by allowing additional options.

**Comment by altrim** [comment]
It's been a while :) but `autoClose` has been added now. As for `onlyOne` it would work only if you had nested component inside another one, so I decided to not expose it for the moment. If I find a better way to handle that I will add it in the future.
