### ISSUE TITLE
Title still shows up

### ISSUE THREAD

**Issue by rwwagner90** [altrim/ember-cli-tooltipster#12]
I'm getting weirdness where the tooltip shows up, but so does the title tooltip.

![screen shot 2015-07-16 at 9 59 01 am](https://cloud.githubusercontent.com/assets/2640861/8725271/54995b08-2ba1-11e5-82dc-95ee091348b1.png)

**Comment by altrim** [comment]
If you are using a computed property for the tooltip I would suggest using the `content` property on the component instead of title. Check the example below it should work. 
```handlebars
{{#tool-tipster content=someProperty}}
    // map icon
{{/tool-tipster}}
```

**Comment by rwwagner90** [comment]
Did not realize that was an option, thanks!
