### ISSUE TITLE
Follow mouse with tooltip

### ISSUE THREAD

**Issue by rwwagner90** [altrim/ember-cli-tooltipster#13]
Is there a way to enable following the mouse with the tooltip?

**Comment by CollinGraves** [comment]
Why not override the positionTracker attribute in a component to the position of your cursor?

**Comment by rwwagner90** [comment]
I'm not using this anymore, but it should still be supported by the library.

**Comment by altrim** [comment]
Closing the issue since Tooltipster doesn't support this feature at the moment.
