### ISSUE TITLE
Regression of 'destroy' call

### ISSUE THREAD

**Issue by Baltazore** [altrim/ember-cli-tooltipster#15]
Hi. Thanks for recent updates. 
In `0.0.11` you add check for presence of initialized `tooltipster` that fix my issues in component integration tests.

In commit [b8ca9d](https://github.com/altrim/ember-cli-tooltipster/commit/b8ca9d5af498413dfa2965b69647ed7e8b29e990#diff-3c3b58ecf16ff0fe536a4ce41f68961cR110) you removed this check and my tests are failing again.

Does any particular reason to remove this check?
Thanks.

**Comment by altrim** [comment]
Hey,

That checking was not correct, it introduced other issues (it reinitialized the tooltipster in the if statement). I have also issues with integration tests, I am not sure why but it looks like in the tests the `willDestroyElement` is called before `didInsertElement` somehow the tootltipster is not getting initialized at all when `willDestroyElement` is called in the tests (or probably the component get's destroyed while tooltipster is being initialized). 

I am trying to find a fix for this but at the moment I am not sure what exactly causes the issue and which is the correct approach to solve this.

**Comment by Baltazore** [comment]
Thanks for clarification. I think we could close this issue.
I have the same issues with `willDestroyElement` for other addons too. One issue that I found is that `parentView` is not available from `willDestroyElement` but you could use `this.$().parent()` and etc.
This one seems to be not related to this project, but all this issues are crazy.

Thanks for fast reply :+1:

**Comment by altrim** [comment]
@Baltazore Fixed this issue in 0.1.2. Now it should work properly.

**Comment by Baltazore** [comment]
@altrim Thanks! Great job!
