### ISSUE TITLE
Using tooltipster with ember-i18n does not work correctly

### ISSUE THREAD

**Issue by mantenie** [altrim/ember-cli-tooltipster#17]
I'm using ember-i18n and try to use tooltipster in my template as
```{{#tool-tipster title="(t 'translation.key')"}}```

This seems to work well and the tooltip shows me the correct text, but the console returns the following error:
```Uncaught TypeError: e.clone is not a function```

**Comment by altrim** [comment]
Hi,

I just tried on a fresh install to use it with ember-i18n everything seems to be working fine. And I am not getting any errors on the console. Are you sure that it's coming from the component?

**Comment by kgish** [comment]
Try `title=(t 'translation.key')` without the double-quotes.
