### ISSUE TITLE
Upgrading from 0.0.11 to 0.1.0 throws a merge error

### ISSUE THREAD

**Issue by chrissvo** [altrim/ember-cli-tooltipster#18]
After upgrading from `0.0.11` to `0.1.0` and run `ember server` I get this error:

Merge error: file `app/styles/app.scss` exists in `/tmp/broccoli_merge_trees-input_base_path-SblWTnuS.tmp/18` and `/tmp/broccoli_merge_trees-input_base_path-SblWTnuS.tmp/28`
Pass option `{ overwrite: true }` to mergeTrees in order to have the latter file win.

I compared the 2 versions https://github.com/altrim/ember-cli-tooltipster/compare/3ce8815...811f764 and I think it is caused by `@import 'ember-paper';`. If I remove that from the add-on my ember app starts, but off course the add-on no longer works ;)

Any suggestions on how I can fix this error?

**Comment by altrim** [comment]
I think that was by mistake, `'ember-paper'` should have been imported only for the demo app. I will remove that and make a new release.

**Comment by altrim** [comment]
@chrissvo Can you try this release https://github.com/altrim/ember-cli-tooltipster/releases/tag/v0.1.3 to check if it works for you ?

**Comment by chrissvo** [comment]
Problem solved, thanks!
