### ISSUE TITLE
Disable native tooltip when using variable in handlebars

### ISSUE THREAD

**Issue by harianus** [altrim/ember-cli-tooltipster#2]
I want to pass a variable to the tooltip helper like this:
```javascript
{{#info-tooltip title="Edit #[...] post" var=post.id}}{{post.title}}{{/info-tooltip}}
```

This is the component:
```javascript
// components/info-tooltip.js
import TooltipsterComponent from 'ember-cli-tooltipster/components/tool-tipster';

var InfoTooltipComponent = TooltipsterComponent.extend({
  tagName: 'span',
  classNames: ['info-tooltip'],
  attributeBindings: ['customTitle:title'],
  customTitle: function() {
    return this.get('title').replace('[...]', this.get('var'));
  }.property('title', 'var')
});

export default InfoTooltipComponent;
```

It looks like this:
![image](https://cloud.githubusercontent.com/assets/1079135/5706341/39a80a72-9a80-11e4-8989-4128ff1828c0.png)

It looks like is does not support a variable in the helper because the double tooltip will not show up when I use it like this:
```javascript
{{#info-tooltip title="Edit #[...] post"}}{{post.title}}{{/info-tooltip}}
```

**Comment by altrim** [comment]
@harianus Hmm strange, I just tested your solution and it seems to work fine.

I get this: 

![screen shot 2015-01-12 at 18 54 36](https://cloud.githubusercontent.com/assets/602300/5707885/d1dc4bb2-9a8c-11e4-9ed4-e440c6f20018.png)

And don't get the native html title attribute at all.

**Comment by harianus** [comment]
Ok, then I will search further... closing for now.

And thanks for testing it!

**Comment by altrim** [comment]
@harianus Same as you used it `var=post.id`, just copy-pasted your code and it worked fine.
