### ISSUE TITLE
Using a component as content

### ISSUE THREAD

**Issue by PowerP** [altrim/ember-cli-tooltipster#20]
Hi,

I'm looking for a way to use a component as content for the tooltip. 

`{{#tool-tipster title=(component 'com' params) ... }}`

this seems not to work. Is it not possible to use a component at all or where is my mistake? 

My stackoverflow question: http://stackoverflow.com/questions/37570246/ember-js-htmlbars-use-component-as-param-of-a-component

thx a lot

**Comment by altrim** [comment]
Yes you are correct you can't use component for the `title/content` of the tooltip. The `content` is expected to be a string. I tried to create a workaround from what I understood from the stackoverflow question. 
Take a look at this repo https://github.com/altrim/tooltipster-content-component 
Is this the behavior you want?

**Comment by PowerP** [comment]
Thx for the quick response. I'm away until Monday and will then check it out and give you more feedback.

**Comment by PowerP** [comment]
Strange. I get always a "Uncaught TypeError: Cannot read property 'getState' of null" exception. I'm using ember 2.2.2. Could there be the problem?

**Comment by PowerP** [comment]
I just realized that when using the option "triggerEvent: 'click'" in your example. the actions are not longer correct called. Where is the problem? 

`export default TooltipsterComponent.extend({
  contentAsHTML: true,
  interactive: true,
  triggerEvent: 'click',
`

**Comment by altrim** [comment]
@PowerP I was just checking this issue and looks like it's in the tooltipster library https://github.com/iamceege/tooltipster/issues/356 and it's only fixed in v4.

**Comment by altrim** [comment]
@PowerP Just to let you know I updated to v4 which fixes the issue with the click. You can update to `0.4.0` to try out the new version. Detailed description of what's changed/removed in the new version you can check here https://github.com/iamceege/tooltipster/issues/566

**Comment by PowerP** [comment]
Thank you. Keep on with the good work!
