### ISSUE TITLE
Support for Tooltipster plugins

### ISSUE THREAD

**Issue by farisj** [altrim/ember-cli-tooltipster#21]
Tooltipster doesn't support the ability to follow cursor positioning, as noted in #13. However, the plugin [tooltipster-follower](https://github.com/louisameline/tooltipster-follower) can add this functionality.

I'd like to be able to use Tooltipster plugins in my Ember Tooltipster Components.

**Comment by altrim** [comment]
Just released the new version which adds support for plugins. 

To use it in your component specify the plugin in `plugins` array. E.g

```
import TooltipsterComponent from 'ember-cli-tooltipster/components/tool-tipster';

export default TooltipsterComponent.extend({
  plugins: ['follower'],
  content: 'My tooltip'
});
```

Make sure also to install the plugin and import it `ember-cli-build.js`.
```
app.import('bower_components/tooltipster-follower/dist/css/tooltipster-follower.min.css');
app.import('bower_components/tooltipster-follower/dist/js/tooltipster-follower.js');
```

**Comment by farisj** [comment]
Awesome! I got it working. Thank you so much for your quick response and update!

**Comment by altrim** [comment]
I guess I can close this issue now, with this fix and your PR looks like it's working great now. Thanks again.
