### ISSUE TITLE
0.4.6 is broken because of missing ember-string-ishtmlsafe-polyfill dependency

### ISSUE THREAD

**Issue by ffaubry** [altrim/ember-cli-tooltipster#31]
ember-string-ishtmlsafe-polyfill should defined as a runtime dependency or should be listed as a prerequisite in the README.md.
Currently, it is listed in the package.json as a devDependency.
The result is that ember-cli-tooltipster is broking projects at runtime if these projects don't already have the ember-string-ishtmlsafe-polyfill as a dependency.
I will propose a PR for making ember-string-ishtmlsafe-polyfill a runtime dependency of ember-cli-tooltipster

**Comment by altrim** [comment]
Merged the PR, thanks for the help. 👍
