### ISSUE TITLE
button onclick event / component event handlers?

### ISSUE THREAD

**Issue by nruth** [altrim/ember-cli-tooltipster#33]
Can we use this to replace a button component, setting an action that is handled by the component or route as usual?

It seems like this is getting swallowed when setting on a `{{#tool-tipster` and there are no examples in the docs of regular component actions /  button usage.

**Comment by altrim** [comment]
When extending `TooltipsterComponent` you also get access to `tooltipsterInstance` and you could set custom `triggerEvent: 'custom'` and then handle open/close in the action  like: 

```
export default TooltipsterComponent.extend({
  tagName: 'button',

  triggerEvent: 'custom',

  content: 'My Tooltip Content',

  click() {
    const tooltip = this.get('tooltipsterInstance');
    tooltip.status().open ? tooltip.close() : tooltip.open();
  }
});
```

**Comment by nruth** [comment]
Thanks for the help, but I'm looking for something simpler and either didn't understand the solution or didn't explain well what I want to do.

Let's say I have a button like this and want to add a tooltip to it:

```
<button {{action 'transitionToNext'}} title="Onwards!">
Next
</button>
```

I'd imagine it should be something like this, but didn't see an example for it and can't get it to work:

```
{{#tool-tipster title="Onwards!" action='transitionToNext')}}
Next
{{/tool-tipster}}
```

or

```
{{#tool-tipster title="Onwards!" onClick=(action 'transitionToNext'))}}
Next
{{/tool-tipster}}
```

The tooltips are working well, but clicking the tooltip component isn't executing the actions like it does for the simple button tag.

This is on ember 2.8/LTS with ember-cli.

**Comment by altrim** [comment]
The second example should work just use 'click` instead of `onClick`

```
{{#tool-tipster title="Onwards!" click=(action 'transitionToNext'))}}
Next
{{/tool-tipster}}
```

**Comment by nruth** [comment]
You're right! Sorry about that. I thought I'd tried it, but was probably combined with another mistake.

**Comment by nruth** [comment]
& thank you for the help!

**Comment by altrim** [comment]
No problem. I'm glad I could help 👍
