### ISSUE TITLE
Removing default CSS

### ISSUE THREAD

**Issue by davidpike7** [altrim/ember-cli-tooltipster#4]
How do I prevent the default CSS being included?

**Comment by altrim** [comment]
I don't think it's possible to prevent that from your side. The tooltipster css is included by default in the addon. If you need other styling you can just override the classes.

**Comment by davidpike7** [comment]
Would it be possible to make this optional? e.g. have a flag in the app config perhaps? I've noticed that done in other Ember CLI plugins.

**Comment by altrim** [comment]
I am including the tooltipster css through `.Brocfile` .  If you can send me a link to an example where they use flag to include css that would be great so I can do the same.

**Comment by davidpike7** [comment]
Ah it would have been in the Brocfile. I can't think of an example off the top of my head but the Ember CLI Autoprefixer plugin allows you to customise some settings inside the Brocfile:

```
var app = new EmberApp({
    autoprefixer: {
        browsers: ['last 5 version'],
        cascade: false
    }
});
```

https://github.com/kimroen/ember-cli-autoprefixer

**Comment by altrim** [comment]
Closing this issue since the css included is required for Tooltipster to work. If you need different theme you just have to overwrite the default one for now.
