### ISSUE TITLE
Tooltipster css import is breaking yarn workspace

### ISSUE THREAD

**Issue by selvaa89** [altrim/ember-cli-tooltipster#43]
I have yarn workspace under which an addon and an application and both of them depends on ember-cli-tooltipster. 

So, yarn rolls up the ember-cli-tooltipster to the root(workspace) directory. But since ember-cli-tooltipster is using project.root, it is still trying to import the css from invalid directory.

This can be fixed by using relative path(require.resolve('tooltipster')).

I will submit a PR for same.

**Comment by altrim** [comment]
Fixed by https://github.com/altrim/ember-cli-tooltipster/pull/44
